API/urls.py
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from . import views


router = DefaultRouter()
router.register(r'User', views.UserViews)
router.register(r'Group', views.Groupviews)
router.register(r'User Info', views.UserInfoviews)
router.register(r'User OTP', views.UserOTPviews)
router.register(r'Topic', views.topicViewSet)
router.register(r'News', views.newsviews)
router.register(r'Report', views.Reportviews)
router.register(r'News Like', views.newsLikeviews)
router.register(r'Following News', views.FollowingNewsTopicviews)
router.register(r'Comments', views.Commentsviews)
router.register(r'Multiple News Image And Video', views.multipleNewsImageAndVideoviews)
router.register(r'Trending Topic', views.TrendingTopicviews)
router.register(r'Bookmarks', views.bookmarksviews)
router.register(r'following Staff', views.followingStaffview)
router.register(r'Office', views.Officeviews)
router.register(r'Staff Member', views.StaffMemberviews)
router.register(r'messeng Staff', views.messengStaffviews)


urlpatterns = [
    path('', include(router.urls)),
]

news24x7/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include("home.urls"),name="index"),
    path('user/', include("customer.urls") ,name="registration"),
     path('tinymce/', include('tinymce.urls')),
      path('ckeditor/', include('ckeditor_uploader.urls')),
     path('panelstaff/', include('staff.urls')),
     path('api/', include("API.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
   path('', views.index,name='panelstaff'),
   path('data/list/', views.datalist),
   path('editnews/<slug>/<id>/', views.editnews),
   path('multipleim/<id>/<news>',views.multipleimedit),
   path('ckeditor/', include('ckeditor_uploader.urls')),
   path('creatdbtbale/', views.creatdbtbale , name='creatdbtbale' ),
   path('Newsdbcreats/', views.Newsdbcreats , name='Newsdbcreats' ),
   path('topicecreatdb/', views.topicecreatdb , name='topicecreatdb' ),
   path('tinymce/', include('tinymce.urls')),
   path('newsvewsqws/<id>/<slug>', views.newsvewsq ),
   path('Writersrandom/<id>', views.Writersrandom ),
   path('Writerssomeone/<id>', views.Writerssomeone ),
   path('somewriter/<id>/<name>/<id2>', views.somewriter ),
   path('editorsrandom/<id>', views.editorsrandom ),
   path('editorsomeone/<id>', views.editorsomeone ),
   path('uservews/<name>/<id>', views.uservews ),

   path('editorsome/<id>/<name>/<id2>', views.editorsome ),
   path('Statistics', views.Statistics,name='Statistics' ),
   path('Statisticsceo/', views.Statisticsceo , name='Statisticsceo' ),
   path('History/', views.History , name='History' ),
   path('Messages/', views.Messages , name='Messages' ),
   path('StaffAll/', views.StaffAll , name='StaffAll' ),
   path('Staffadd/', views.Staffadd , name='Staffadd' ),
   path("creatStaff/", views.Staffcreate , name="Staffcreate" ),
   path("creatStaff/<pk>", views.Staffcreate2 , name="Staffcreate2" )
   

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

class UserOTP(models.Model):
    email = models.EmailField(unique=True)
    is_email_verified = models.BooleanField(default=False)
    email_otp = models.CharField(max_length=6, null=True, blank=True)

class UserInfo(models.Model):
    Ganderschoices =(
        ("Male","Male"),
        ("Other","Other"),
        ("Female","Female"),
    )
    UserName = models.OneToOneField(User , on_delete=models.CASCADE)
    Ganders = models.CharField(choices=Ganderschoices,max_length=15)
    address = models.CharField(max_length=150 ,blank=True,null=True)
    picture = models.ImageField(upload_to="picture/",blank=True,null=True)

staff/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

class Office(models.Model):
    address = models.CharField(max_length=200,unique=True)
    manger = models.CharField(max_length=100)
    def __str__(self):
        return self.address

class StaffMember(models.Model):
    choicesPosition = (
        ("none","none"),
        ("Admin","Admin"),
        ("CEO","CEO"),
        ('Manager','Manager'),
        ("SalesManager","SalesManager"),
        ("TechicalDirectors","TechicalDirectors"),
        ("NewsDirectors","NewsDirectors"),
        ("HR","HR"),
        ("NewsAnchors","NewsAnchors"),
        ("Newsdirector","Newsdirector"),
        ("Producers","Producers"),
        
        ("Reporters","Reporters"),
        ("SeniorReporters","SeniorReporters"),
        ("JuniorReporters","JuniorReporters"),
        
        ("Journalists","Journalists"),
        ("SeniorJournalists","SeniorJournalists"),
        ("JuniorJournalists","JuniorJournalists"),
        
        ("CameraMan","CameraMan"),
        ("CameraOperators","CameraOperators"),
        ("PhotoJournalists","PhotoJournalists"),
        
        ("SeniorEditors","SeniorEditors"),
        ("Editors","Editors"),
        ("JuniorEditors","JuniorEditors"),


        ("Editors","Editors"),
        ("AudioEditors","AudioEditors"),
        ("AudioEngineer","AudioEngineer"),
        
        ("Seniorwriters","Seniorwriters"),
        ('writers','writers'),
        ("Juniorwriters","Juniorwriters"),
        
        ("AssignmentEditors","AssignmentEditors"),
        ("GraphicDesigners","GraphicDesigners"),
        ("BroadcastEngineer","BroadcastEngineer"),
        ("LightingTechnician","LightingTechnician"),
        ("GraphicDesigner","GraphicDesigner"),
        ("MakeupArtist","MakeupArtist"),
        ("TechnicalStaff","TechnicalStaff"),
        ("SupportStaff","SupportStaff"),
    )
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    staff_name = models.CharField(max_length=200)
    Office = models.ForeignKey(Office,on_delete=models.CASCADE)
    position = models.CharField(choices=choicesPosition ,max_length=100)
    DateOfBirth = models.DateField()
    PhoneNumber = models.CharField(max_length=100)
    ZipCode = models.CharField(max_length=15)
    OneAddress = models.TextField(max_length=350)
    TwoAddress = models.TextField(max_length=350 ,blank=True,null=True)
    picture = models.FileField(upload_to="StaffMember/")
    JoinDate = models.DateField()
    LeaveDate = models.DateField(blank=True,null=True)
    aboutme = HTMLField(blank=True,null=True)
    def __str__(self):
        return self.staff_name


class messengStaff(models.Model):
    user = models.ForeignKey(StaffMember,on_delete=models.CASCADE ,related_name="User")
    OthrtUserName = models.ForeignKey(StaffMember,on_delete=models.CASCADE , related_name="OthrtUserName")
    Txt = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
   

staff/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import StaffMember,messengStaff
from datetime import date, timedelta
from home.models import News,Topic,multipleNewsImageAndVideo,followingStaff,TrendingTopic
from customer.models import UserInfo,UserOTP
from django.contrib.auth.models import User,Group
from .forms import NewsImagedb,multipleNewsImageAndVideodbform,Usercreated
import os
import random
import string
from customer.forms import RegisterForm,UserInfoForm
from .forms import StaffMemberdb
from customer.forms import RegisterForm
from customer.models import UserInfo

def index(request):
    if request.user.is_staff == False:return redirect('/')
    today = date.today()
    newsallgb  = News.objects.all()[::-1]
    userdb = StaffMember.objects.get(user=request.user)
    meaxax = messengStaff.objects.all().filter(OthrtUserName=userdb)
    
    if userdb.position in ['SpecialReporters','SeniorReporters','JuniorReporters','SpecialJournalists','SeniorJournalists','JuniorJournalists']:
        newsgb = News.objects.all().filter(Journalists=userdb,JournalistsPermission=True)
        newsallgb  = News.objects.all().filter(Journalists=userdb,JournalistsPermission=None)[::-1]
       
    
    
    if userdb.position in ["SeniorEditors","JuniorEditors","Editors"]:
        newsgb = News.objects.all().filter(Editors=userdb,EditorsPermission=True)
        newsallgb =  News.objects.all().filter(Editors=None,EditorsPermission=None,WritersPermission=True,JournalistsPermission=True)[::-1]
    
    if userdb.position in ["Scriptwriters","Seniorwriters","Juniorwriters"]:
        newsgb = News.objects.all().filter(Writers=userdb,WritersPermission=True)
        newsallgb =  News.objects.all().filter(JournalistsPermission=True,Writers=None)
    if userdb.position in ["Manager","CEO"]:
        newsgb = News.objects.all().filter(Writers=userdb,WritersPermission=True)
        newsallgb =  News.objects.all().filter(JournalistsPermission=True,WritersPermission=True,EditorsPermission=True)[::-1]
    

    try:
        previous_date = today - timedelta(days=0)
        data1 = newsgb.filter(CreatDate=previous_date.strftime("%Y-%m-%d")).count()
        dataday1 = previous_date.strftime("%Y-%b-%d")
        previous_date = today - timedelta(days=1)
        data2 = newsgb.filter(CreatDate=previous_date.strftime("%Y-%m-%d")).count()
        dataday2 = previous_date.strftime("%Y-%b-%d")
        previous_date = today - timedelta(days=2)
        data3 = newsgb.filter(CreatDate=previous_date.strftime("%Y-%m-%d")).count()
        dataday3 = previous_date.strftime("%Y-%b-%d")
        previous_date = today - timedelta(days=3)
        data4 = newsgb.filter(CreatDate=previous_date.strftime("%Y-%m-%d")).count()
        dataday4 = previous_date.strftime("%Y-%b-%d")
        previous_date = today - timedelta(days=4)
        data5 = newsgb.filter(CreatDate=previous_date.strftime("%Y-%m-%d")).count()
        dataday5 = previous_date.strftime("%Y-%b-%d")
        previous_date = today - timedelta(days=5)
        data6 = newsgb.filter(CreatDate=previous_date.strftime("%Y-%m-%d")).count()
        dataday6 = previous_date.strftime("%Y-%b-%d")
        previous_date = today - timedelta(days=5)
        data7 = newsgb.filter(CreatDate=previous_date.strftime("%Y-%m-%d")).count()
        dataday7 = previous_date.strftime("%Y-%b-%d")
    except:
        newsgb = ""
        data1 = 0
        data2 = 0
        data3 = 0
        data4 = 0
        data5 = 0
        data6 = 0
        data7 = 0
        dataday1 = 'none'
        dataday2 = 'none'
        dataday3 = 'none'
        dataday4 = 'none'
        dataday5 = 'none'
        dataday6 = 'none'
        dataday7 = 'none'
        
    
    data ={
        'meaxax':meaxax,
        'userdb':userdb,
        'newsgb':newsgb,
        'data1':data1,
        'dataday1':dataday1,
        'data2':data2,
        'dataday2':dataday2,
        'data3':data3,
        'data4':data4,
        'dataday3':dataday3,
        'dataday4':dataday4,
        'data5':data5,
        'dataday5':dataday5,
        'data6':data6,
        'dataday6':dataday6,
        'data7':data7,
        'dataday7':dataday7,
        "newsallgb":newsallgb,

    }
    return render(request ,'staff/index.html',data)


def newsvewsq(request,id,slug):
    if request.user.is_staff == False:return redirect('/')
    userdb = StaffMember.objects.get(user=request.user)
    newsdb = News.objects.get(id=id)
    mutple = multipleNewsImageAndVideo.objects.all().filter(news=newsdb)
    data ={
        "userdb":userdb,
        'newsdb':newsdb,
        'mutple':mutple
    }
    return render(request ,'staff/newsvewsq.html',data)

def datalist(request):
    if request.user.is_staff == False:return redirect('/')
    userdb = StaffMember.objects.get(user=request.user)
    newsgb =''
    
    if userdb.position in ['SpecialReporters','SeniorReporters','JuniorReporters','SpecialJournalists','SeniorJournalists','JuniorJournalists',"Journalists"]:
        newsgb = News.objects.all().filter(Journalists=userdb)

        qadqw =['Seniorwriters','writers','Juniorwriters']
        userdball = StaffMember.objects.all().filter(position__in=qadqw)
        random_element = random.choice(userdball)
        if request.method == 'POST':
            NotSubmit = request.POST.getlist("NotSubmit")
            action = request.POST.get("action")
            Rejected = request.POST.getlist("Rejected")
            action2 = request.POST.get("action2")

            if action2 == '1':
                for x in Rejected:
                    newsdb = News.objects.get(id=int(x))
                    newsdb.delete()
                return redirect('/panelstaff/data/list/')
            if action2 == '2':
                for x in Rejected:
                    newsdb = News.objects.get(id=int(x))
                    newsdb.JournalistsPermission = None
                    newsdb.save()
                return redirect('/panelstaff/data/list/')
            
            if action == '1':
                for x in NotSubmit:
                    newsdb = News.objects.get(id=int(x))
                    newsdb.JournalistsPermission = True
                    newsdb.Writers =random_element
                    newsdb.save()
                return redirect('/panelstaff/data/list/')
            if action == '2':
                for x in NotSubmit:
                    newsdb = News.objects.get(id=int(x))
                    newsdb.JournalistsPermission = False
                    newsdb.save()
                return redirect('/panelstaff/data/list/')
           
        Journalistsdata = {
            'newsgb':newsgb,
            'userdb':userdb
        }
        return render(request ,'staff/Journalists.html',Journalistsdata)

    if userdb.position in ["SeniorEditors","JuniorEditors","Editors"]:
        userdb = StaffMember.objects.get(user=request.user)
        newsgb = News.objects.all().filter(Editors=userdb)
        newsgb = News.objects.all().filter(Editors=userdb,EditorsPermission=None)[::-1]
        newsgbss = News.objects.all().filter(Editors=userdb,EditorsPermission=False)[::-1]
        newsgbTrue = News.objects.all().filter(Editors=userdb,EditorsPermission=True)[::-1]
        if request.method == 'POST':
            Rejected = request.POST.getlist("Rejected")
            action = request.POST.get("action")
            action2 = request.POST.get("action2")
            Rejected1 = request.POST.getlist("Rejected1")
               
                 
            if action == '2':
                for x in Rejected:
                    qadqw =["SeniorEditors","JuniorEditors","Editors"]
                    userdballs = StaffMember.objects.all().filter(position__in=qadqw)
                    random_element = random.choice(userdballs)
                    newsfr = News.objects.get(id = int(x))
                    newsfr.Editors = random_element
                    newsfr.save()
                return redirect('/panelstaff/data/list/')
            
            if action == '1':
                for x in Rejected:
                    qadqw =["SeniorEditors","JuniorEditors","Editors"]
                    userdballs = StaffMember.objects.all().filter(position__in=qadqw)
                    random_element = random.choice(userdballs)
                    newsfr = News.objects.get(id = int(x))
                    newsfr.EditorsPermission = False
                    newsfr.save()
                return redirect('/panelstaff/data/list/')
            
            if action2 == '3':
                for x in Rejected1:
                    newsfr = News.objects.get(id = int(x))
                    qadqw =["SeniorEditors","JuniorEditors","Editors"]
                    userdballs = StaffMember.objects.all().filter(position__in=qadqw)
                    random_element = random.choice(userdballs)
                    newsfr.EditorsPermission = True
                
                    newsfr.save()
                return redirect('/panelstaff/data/list/')
            
            if action2 == '2':
                for x in Rejected1:
                    qadqw =["SeniorEditors","JuniorEditors","Editors"]
                    userdballs = StaffMember.objects.all().filter(position__in=qadqw)
                    random_element = random.choice(userdballs)
                    newsfr = News.objects.get(id = int(x))
                    newsfr.Editors = random_element
                    newsfr.save()
                return redirect('/panelstaff/data/list/')
                
        data ={
            "userdb":userdb,
            'newsgb':newsgb,
            'newsgbss':newsgbss,
            'newsgbTrue':newsgbTrue
        }
        return render(request ,'staff/writersdb.html',data)

    

templates/page/profile.html
{% extends 'main.html' %}

{% block title %}
    profile
{% endblock title %}



{% block body %}
<style>
.video-background {
  position: fixed;
  object-fit: fill;
  margin: 0;
  z-index: -99;
}
.glass-effect {
  background-color: rgba(255, 255, 255, 0.15);   
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px); 
  border: 1px solid rgba(255, 255, 255, 0.3);
  box-shadow: 0 4px 30px rgba(243, 229, 229, 0.1);
  border-radius: 16px;
}

</style>
<video class="video-background " src="/static/image/zero.mp4" autoplay loop muted ></video>
<div class="container-fluid row pt-5 mb-3 justify-content-center">
<div class="col-10 row justify-content-center">
<div class="col-sm-8 glass-effect text-white ">
    <div class="row justify-content-center">
        <div class="col-12 text-end text-white">
            <a href="/" class="text-white" style="font-size: 32px;">
                <i class="bi bi-x-lg"></i>
            </a>
        </div>
        <div class="col-12 pt-3 pb-3"> 
            <center>
                
                {% if user.userinfo.picture != ""  %}
                <img style="width: 250px; height: 250px; aspect-ratio: 1 / 1; "  src="/media/{{user.userinfo.picture}}" class="rounded-circle" alt=""> 
                {% else %}
                <img style="width: 250px; height: 250px; aspect-ratio: 1 / 1; "  src="/static/image/profile.webp" class="rounded-circle" alt=""> 
                {% endif %}
            </center>
        </div>
        <div class="col-12 text-white fs-5 text-break text-wrap  ">
            Name: {{user.username}}  <br>
            Email: {{user.email }} <br>
            Ganders: {{user.userinfo.Ganders }} 
            
            {% if user.userinfo.Ganders == 'Male'  %}
                <i class="bi bi-gender-male"></i>
            {% endif %}
            
            {% if user.userinfo.Ganders == 'Female'  %}
            <i class="bi bi-gender-female"></i>
            {% endif %}
            {% if user.userinfo.Ganders == 'Other'  %}
   <i class="bi bi-gender-neuter"></i>         
            {% endif %}
                
            <br>
        </div>
        <div class="col-12 pb-5 pt-5">
            <div class=" justify-content-around row">
<button style="width: fit-content;" type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
<i class="bi bi-pencil-fill"></i> Edit
</button>
                

{% if user.is_staff %}

<a href="/panelstaff/" class="bg-success text-white btn " style="width: fit-content;">
    <i class="bi bi-layers-fill"></i> 
    
    Admin
</a>

{% endif %}
                
                    
                <a href="{% url 'logout' %}" class="btn btn-danger" style="width: fit-content;"><i class="bi bi-box-arrow-left"></i> Logout</a>
            </div>
        </div>
    </div>
</div>
</div>
</div>

<!-- Modal -->
<div  style="background-color: rgba(0, 0, 0, 0.33);" class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Profile Edit</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <script>
            $(document).ready(function(){

                $("#id_picture").hide()
            })
        </script>
       <form action="" enctype="multipart/form-data" method="post">
{% csrf_token %}
<label style="border-style: dotted !important ; background-color: #0dcaf04e; font-size: 32px;  " for="{{dbform.picture.id_for_label }}" class=" w-100 border-3 border border-dark  text-center pt-5 pb-5">
    <i class="bi bi-image"></i>
</label> <br>

<span class="d-none">
    {{dbform.picture}}
</span>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>
    </div>
  </div>
</div>
{% endblock body %}
    

templates/page/register.html

{% extends 'main.html' %}



{% block title %}
  Registration
{% endblock title %}
  
{% block body %}
<script>
  	$(document).ready(function(){
    $(".hie65").hide();
        $('#result0').click(function(){
            if($(this).prop("checked") == true){
                  var x = document.getElementById("checked0");
                  x.type = "submit";
                   $(".hie65").hide();
                }
                else if($(this).prop("checked") == false){
                  var x = document.getElementById("checked0");
                  x.type = "button";
               
            }
        });
        $('.subp88').click(function(){
          var x = document.getElementById("checked0");
          if (x.type == "button"){
             $(".hie65").show();
          }
        });
    });
</script>
<style>
  .form-check-input:checked {
    background-color: #f1eeee;
    border-color: #e8d7dc;
}
.form-check-input:focus {
    border-color: #ece6e6;
    box-shadow: 0 0 0 .25rem rgba(36, 35, 35, 0.25);
}
.form-control:focus {
    color: var(--bs-body-color);
    background-color: var(--bs-body-bg);
    border-color: #e2d2d2;
    outline: 0;
    box-shadow: 0 0 0 .25rem rgba(187, 182, 182, 0.25);
}
.glass-effect {
  background-color: rgba(255, 255, 255, 0.15);   
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px); 
  border: 1px solid rgba(255, 255, 255, 0.3);
  box-shadow: 0 4px 30px rgba(244, 239, 239, 0.1);
  border-radius: 16px;
}

</style>
<div class="container-fluid h-100" style="background-image: url(/static/image/What12.jpeg); background-size: cover; background-attachment: fixed; ">
  <div class="row justify-content-center">
<form action="" method="post" class=" text-white border-0 glass-effect col-10  mt-5 mb-5 p-3 rounded ">
  {% csrf_token %}
  <div class="col-12 mb-5">
    <div class="row justify-content-center">
      <img src="/static/image/logo.svg" class="col-md-6" alt="">
    </div>
  </div>
  <input type="text" name="latitude" value="" id="latitude" hidden>
  <input type="text" value="" name="longitude" id="longitude" hidden>
  <div class="row justify-content-around">
  <div class=" m-2 col-5 ">
    {{userform.username.label_tag}} <br>
    {{userform.username}} <br>
  </div>
  <div class="m-2 col-5 ">
    {{userform.email.label_tag}} <br>
    {{userform.email}} <br>
  </div>
  <div class=" m-2  col-5">
    {{userform.password1.label_tag}} <br>
    {{userform.password1}} <br>
  </div>
  <div class=" m-2 col-5">

    {{userform.password2.label_tag}} <br>
    {{userform.password2}} <br>
  </div>
  <div class="form-check col-11">
    <span class="ps-0 ms-0">
      Gender select
    </span> <br>
    
    <br>
    
    
    <input type="radio" value="Male" class="btn-check" name="Ganders" id="Male" autocomplete="off" checked >
    <label class="btn btn-outline-light rounded-0 p-2 ps-3 pe-3 " for="Male">
      <span style="font-size: 32px;"><i class="bi bi-gender-male"></i></span>  <br>
      <span style="font-size: 16px;">Male</span> 
    </label>
    
    <input value="Female" type="radio" class="btn-check" name="Ganders" id="Female" autocomplete="off">
    <label class="btn btn-outline-light rounded-0 p-2 ps-3 pe-3 " for="Female">
      <span style="font-size: 32px;" ><i class="bi bi-gender-female"></i></span> <br>  
      <span style="font-size: 16px;">Female</span>
    </label>
    
    <input value="Other" type="radio" class="btn-check" name="Ganders" id="Other" autocomplete="off">
    <label class="btn btn-outline-light rounded-0 p-2 ps-4 pe-4 " for="Other">
      <span style="font-size: 32px;"><i class="bi bi-gender-trans"></i></span> <br>
      <span style="font-size: 16px;" >Other</span>
    </label>
  </div>

  </div>
  <div class="text-danger fw-blod mt-1">

     {{ usererros  }} 

     
      
  </div>
   <div class="col-12 pt-3">
<div class="form-check">
  <input class="form-check-input chaccik65 " style="background-color: black;" type="checkbox" id="result0" >
  <label class="form-check-label fw-lighter " for="checkDefault">
    I agree The <a href="/aboutus/" class="text-danger "> click here read more News24x7</a>
  </label>
</div>
                                </div>
                                <div class=" text-danger fs-6 hie65 " style="width: fit-content;" role="alert">
                          Please Check The I Agree
                          </div>
 <div class="col-12 mb-3 mt-5 row justify-content-evenly">
   <a style="width: fit-content;" href="{% url 'login' %}" class="btn btn-dark " ><i class="bi bi-box-arrow-in-left"></i> Login</a>
   <a  style="width: fit-content;" onclick="showpassworda()" class="btn-light btn showaall " id="togglePassword" >
    <i class="bi bi-eye-fill"></i> Show
   </a> 
   <button type="button" style="width: fit-content;" class="btn btn-outline-light subp88 " name="" id="checked0" >
    <i class="bi bi-cursor-fill"></i> Submit
   </button>

  </div>
</form>
  </div>
</div>

<script>
  function showpassworda() {
  var x = document.getElementById("id_password2");
  var y = document.getElementById("id_password1");
  if (x.type === "password") {
    x.type = "text";
    y.type = "text";
     $(".showaall").html("<i class='bi bi-eye-slash-fill'></i> Hied");
  } else {
    x.type = "password";
    y.type = "password";
     $(".showaall").html("<i class='bi bi-eye-fill'></i> Show");
  }
}
</script>
<style>
  #id_username,#id_email,#id_password1,#id_password2{
    background-color: transparent;
    color: white;
    font-weight: bold;
    letter-spacing: 1.5px; 
  }
</style>
<script>

$("#id_username").addClass("form-control");
$("#id_email").addClass("form-control");
$("#id_password1").addClass("form-control");
$("#id_password2").addClass("form-control");
const x = document.getElementById("demo");
getLocation();
function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.watchPosition(success, error);
  } else { 
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}
    
function success(position) {
    x.innerHTML="Latitude: " + position.coords.latitude + 
    "<br>Longitude: " + position.coords.longitude;
    console.log( position.coords.latitude) ;
    console.log( position.coords.longitude);
    console.log(document.cookie);
    $("#latitude").val( position.coords.latitude);
    $("#longitude").val( position.coords.longitude);
}

function error(error) {
  switch(error.code) {
    case error.PERMISSION_DENIED:
      x.innerHTML = "User denied the request for Geolocation."
      break;
    case error.POSITION_UNAVAILABLE:
      x.innerHTML = "Location information is unavailable."
      break;
    case error.TIMEOUT:
      x.innerHTML = "The request to get user location timed out."
      break;
    case error.UNKNOWN_ERROR:
      x.innerHTML = "An unknown error occurred."
      break;
  }
}
</script>
{% endblock body %}
  