API/urls.py
from django.urls import path,include
from rest_framework.routers import DefaultRouter
from . import views


router = DefaultRouter()
router.register(r'User', views.UserViews)
router.register(r'Group', views.Groupviews)
router.register(r'User Info', views.UserInfoviews)
router.register(r'User OTP', views.UserOTPviews)
router.register(r'Topic', views.topicViewSet)
router.register(r'News', views.newsviews)
router.register(r'Report', views.Reportviews)
router.register(r'News Like', views.newsLikeviews)
router.register(r'Following News', views.FollowingNewsTopicviews)
router.register(r'Comments', views.Commentsviews)
router.register(r'Multiple News Image And Video', views.multipleNewsImageAndVideoviews)
router.register(r'Trending Topic', views.TrendingTopicviews)
router.register(r'Bookmarks', views.bookmarksviews)
router.register(r'following Staff', views.followingStaffview)
router.register(r'Office', views.Officeviews)
router.register(r'Staff Member', views.StaffMemberviews)
router.register(r'messeng Staff', views.messengStaffviews)


urlpatterns = [
    path('', include(router.urls)),
]

news24x7/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include("home.urls"),name="index"),
    path('user/', include("customer.urls") ,name="registration"),
     path('tinymce/', include('tinymce.urls')),
      path('ckeditor/', include('ckeditor_uploader.urls')),
     path('panelstaff/', include('staff.urls')),
     path('api/', include("API.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
   path('', views.index,name='panelstaff'),
   path('data/list/', views.datalist),
   path('editnews/<slug>/<id>/', views.editnews),
   path('multipleim/<id>/<news>',views.multipleimedit),
   path('ckeditor/', include('ckeditor_uploader.urls')),
   path('creatdbtbale/', views.creatdbtbale , name='creatdbtbale' ),
   path('Newsdbcreats/', views.Newsdbcreats , name='Newsdbcreats' ),
   path('topicecreatdb/', views.topicecreatdb , name='topicecreatdb' ),
   path('tinymce/', include('tinymce.urls')),
   path('newsvewsqws/<id>/<slug>', views.newsvewsq ),
   path('Writersrandom/<id>', views.Writersrandom ),
   path('Writerssomeone/<id>', views.Writerssomeone ),
   path('somewriter/<id>/<name>/<id2>', views.somewriter ),
   path('editorsrandom/<id>', views.editorsrandom ),
   path('editorsomeone/<id>', views.editorsomeone ),
   path('uservews/<name>/<id>', views.uservews ),

   path('editorsome/<id>/<name>/<id2>', views.editorsome ),
   path('Statistics', views.Statistics,name='Statistics' ),
   path('Statisticsceo/', views.Statisticsceo , name='Statisticsceo' ),
   path('History/', views.History , name='History' ),
   path('Messages/', views.Messages , name='Messages' ),
   path('StaffAll/', views.StaffAll , name='StaffAll' ),
   path('Staffadd/', views.Staffadd , name='Staffadd' ),
   path("creatStaff/", views.Staffcreate , name="Staffcreate" ),
   path("creatStaff/<pk>", views.Staffcreate2 , name="Staffcreate2" )
   

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from staff.models import StaffMember
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from autoslug import AutoSlugField
from staff.models import StaffMember


class Topic(models.Model):
    Topic = models.CharField(max_length=20,unique=True)
    Date = models.DateField(auto_now_add=True)
    CreatedBy = models.ForeignKey(StaffMember,on_delete=models.DO_NOTHING)
    def __str__(self):
        return self.Topic

class News(models.Model):
    Topic = models.ForeignKey(Topic ,on_delete=models.CASCADE,blank=True,null=True)
    Journalists = models.ForeignKey(StaffMember,related_name="Journalists",on_delete=models.CASCADE,default="sorry",blank=True,null=True)
    Writers = models.ForeignKey(StaffMember,related_name="Writers",on_delete=models.CASCADE,default="sorry" ,blank=True,null=True)
    Editors = models.ForeignKey(StaffMember,related_name="Editors",on_delete=models.CASCADE,default="sorry",blank=True,null=True)
    NewsTitle = models.CharField(max_length=250,blank=True,null=True)
    Txt =   HTMLField(blank=True,null=True)
    Image = models.ImageField(upload_to="image/",blank=True,null=True)
    Video = models.FileField(upload_to="video/",blank=True,null=True)
    CreatDate = models.DateField(auto_now_add=True)
    onlyvideo = models.BooleanField(default=False)
    JournalistsPermission = models.BooleanField(blank=True,null=True)
    WritersPermission = models.BooleanField(blank=True,null=True )
    EditorsPermission = models.BooleanField(blank=True,null=True )
    ManagersPermission = models.BooleanField(blank=True,null=True )
    slug = AutoSlugField(populate_from='NewsTitle')
    # Collaboration = models.ManyToManyField(StaffMember,blank=True)
    def __str__(self):
        return self.NewsTitle
    

class Report(models.Model):
    News = models.ForeignKey(News,on_delete=models.CASCADE)
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    Title = models.CharField(max_length=75)
    Txt = models.TextField(max_length=500)
    slug = AutoSlugField(populate_from='Txt')

class newsLike(models.Model):
    News = models.OneToOneField(News ,on_delete=models.CASCADE)
    User = models.ManyToManyField(User,blank=True)

class FollowingNewsTopic(models.Model):
    NewsTopic = models.OneToOneField(Topic,on_delete=models.CASCADE)
    User = models.ManyToManyField(User,blank=True)

class Comments(models.Model):
    UserName = models.ForeignKey(User,on_delete=models.CASCADE)
    news = models.ForeignKey(News , on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateField(auto_now_add=True)
    slug = AutoSlugField(populate_from='text')

class multipleNewsImageAndVideo(models.Model):
    news = models.ForeignKey(News , on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image/", blank=True ,null=True)
    video = models.FileField(upload_to="video/" , blank=True ,null=True)

class TrendingTopic(models.Model):
    NewsTopic = models.OneToOneField(Topic,on_delete=models.CASCADE) 
    Date = models.DateTimeField(auto_now_add=True)


# class ReplyByNews24x7(models.Model):
#     to = models.ForeignKey(User,on_delete=models.CASCADE)
#     txt = HTMLField()
#     date = models.DateField(auto_now_add=True)
#     slug = AutoSlugField(populate_from='txt')

# class Countus(models.Model):
#     user = models.ForeignKey(User ,on_delete=models.CASCADE)
#     title = models.CharField(max_length=100)
#     txt = models.TextField(max_length=500)
#     slug = AutoSlugField(populate_from='title')

# class NewsBlogPage(models.Model):
#     title = models.CharField(max_length=50)
#     image = models.ImageField(upload_to="image/")
#     txt = HTMLField()
#     date = models.DateField(auto_now_add=True)
#     slug = AutoSlugField(populate_from='title')


class bookmarks(models.Model):
    News = models.OneToOneField(News,on_delete=models.CASCADE)
    User = models.ManyToManyField(User,blank=True,default="")

class followingStaff(models.Model):
    StaffMemberName = models.OneToOneField(StaffMember,on_delete=models.CASCADE)
    User = models.ManyToManyField(User,blank=True,default="")

staff/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

class Office(models.Model):
    address = models.CharField(max_length=200,unique=True)
    manger = models.CharField(max_length=100)
    def __str__(self):
        return self.address

class StaffMember(models.Model):
    choicesPosition = (
        ("none","none"),
        ("Admin","Admin"),
        ("CEO","CEO"),
        ('Manager','Manager'),
        ("SalesManager","SalesManager"),
        ("TechicalDirectors","TechicalDirectors"),
        ("NewsDirectors","NewsDirectors"),
        ("HR","HR"),
        ("NewsAnchors","NewsAnchors"),
        ("Newsdirector","Newsdirector"),
        ("Producers","Producers"),
        
        ("Reporters","Reporters"),
        ("SeniorReporters","SeniorReporters"),
        ("JuniorReporters","JuniorReporters"),
        
        ("Journalists","Journalists"),
        ("SeniorJournalists","SeniorJournalists"),
        ("JuniorJournalists","JuniorJournalists"),
        
        ("CameraMan","CameraMan"),
        ("CameraOperators","CameraOperators"),
        ("PhotoJournalists","PhotoJournalists"),
        
        ("SeniorEditors","SeniorEditors"),
        ("Editors","Editors"),
        ("JuniorEditors","JuniorEditors"),


        ("Editors","Editors"),
        ("AudioEditors","AudioEditors"),
        ("AudioEngineer","AudioEngineer"),
        
        ("Seniorwriters","Seniorwriters"),
        ('writers','writers'),
        ("Juniorwriters","Juniorwriters"),
        
        ("AssignmentEditors","AssignmentEditors"),
        ("GraphicDesigners","GraphicDesigners"),
        ("BroadcastEngineer","BroadcastEngineer"),
        ("LightingTechnician","LightingTechnician"),
        ("GraphicDesigner","GraphicDesigner"),
        ("MakeupArtist","MakeupArtist"),
        ("TechnicalStaff","TechnicalStaff"),
        ("SupportStaff","SupportStaff"),
    )
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    staff_name = models.CharField(max_length=200)
    Office = models.ForeignKey(Office,on_delete=models.CASCADE)
    position = models.CharField(choices=choicesPosition ,max_length=100)
    DateOfBirth = models.DateField()
    PhoneNumber = models.CharField(max_length=100)
    ZipCode = models.CharField(max_length=15)
    OneAddress = models.TextField(max_length=350)
    TwoAddress = models.TextField(max_length=350 ,blank=True,null=True)
    picture = models.FileField(upload_to="StaffMember/")
    JoinDate = models.DateField()
    LeaveDate = models.DateField(blank=True,null=True)
    aboutme = HTMLField(blank=True,null=True)
    def __str__(self):
        return self.staff_name


class messengStaff(models.Model):
    user = models.ForeignKey(StaffMember,on_delete=models.CASCADE ,related_name="User")
    OthrtUserName = models.ForeignKey(StaffMember,on_delete=models.CASCADE , related_name="OthrtUserName")
    Txt = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
   

staff/forms.py
from django import forms
from django.contrib.auth.models import User,Group
from home.models import News,multipleNewsImageAndVideo,Topic
from .models import StaffMember
from customer.models import UserInfo
class multipleNewsImageAndVideodbform(forms.ModelForm):
    class Meta:
        model = multipleNewsImageAndVideo
        fields = ['image','video']
class NewsImagedb(forms.ModelForm):
    class Meta:
        model = News
        fields = ['Image', 'Video']
      


class StaffMemberdb(forms.ModelForm):
    class Meta:
        model = StaffMember
        fields = '__all__'

class Usercreated(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'

templates/staff/Manager.html
{% extends 'main.html' %}


{% block title %}
    Data List
{% endblock title %}
{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-6 pt-5">
             <table class="table">
                <thead>
                
                <tr>
                    <th class="bg-dark text-white" colspan="3">
                       Request
                    </th>
                </tr>
            </thead>
            <tbody>
                
                {% for x in newsTruegb|slice:":50:"  %}
                <tr>
                    <td>
                        <a href="/panelstaff/newsvewsqws/{{x.id}}/{{x.slug}}">
                                {{x.NewsTitle}}
                    </a></td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
       
            <!--  -->
            
<form  method="POST">
  {% csrf_token %}
  <table class="table mt-5">
      <thead>
          <tr>
              <th>
                        <select name="action" class="form-select" aria-label="Default select example">
                            <option selected>Action Select </option>
                            <option value="1">Submit Select </option>
                            <option value="2">Reject</option>
                        </select>
                    </th>
                    <th>
                        <input type="submit" class="btn btn-dark">
                    </th>
                </tr>
                <tr>
                    <th class="bg-dark text-white" colspan="3">
                        <input type="checkbox"  id="selectAllCheckbox2" value=""> Request
                    </th>
                </tr>
            </thead>
            <tbody>
                
                {% for x in newsgb  %}
                <tr>
                    <td><input name="Rejected" value="{{x.id}}" class="individualCheckbox2" type="checkbox" multiple>
                        <a href="/panelstaff/newsvewsqws/{{x.id}}/{{x.slug}}">
                            {{x.NewsTitle}}
                        </a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
</form>

<form  method="POST">
  {% csrf_token %}
            <table class="table mt-5">
                <thead>
                <tr>
                    <th>
                        <select name="action2" class="form-select" aria-label="Default select example">
                        <option selected>Action Select </option>
                        <option value="1">Submit Select </option>
                        
                    </select>
                </th>
                <th>
                    <input type="submit" class="btn btn-dark">
                </th>
                </tr>
                <tr>
                    <th class="bg-dark text-white" colspan="3">
                       <input type="checkbox"  id="selectAllCheckbox3" value=""> Reject
                    </th>
                </tr>
            </thead>
            <tbody>
                
                {% for x in newsFalsegb  %}
                <tr>
                    <td><input name="Rejected2" value="{{x.id}}" class="individualCheckbox3" type="checkbox" multiple>
                        <a href="/panelstaff/newsvewsqws/{{x.id}}/{{x.slug}}">
                                {{x.NewsTitle}}
                    </a></td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
</div>
</form>

<DIV class="p-5 m-5 "></DIV>
<script>
     $(document).ready(function() {
        $('#selectAllCheckbox2').on('change', function() {
            var isChecked = $(this).prop('checked');
            $('.individualCheckbox2').prop('checked', isChecked);
        });
        $('.individualCheckbox2').on('change', function() {
            var allChecked = $('.individualCheckbox2:checked').length === $('.individualCheckbox').length;
            $('#selectAllCheckbox2').prop('checked', allChecked);
        });
    });
</script>
<script>
     $(document).ready(function() {
        $('#selectAllCheckbox3').on('change', function() {
            var isChecked = $(this).prop('checked');
            $('.individualCheckbox3').prop('checked', isChecked);
        });
        $('.individualCheckbox3').on('change', function() {
            var allChecked = $('.individualCheckbox3:checked').length === $('.individualCheckbox').length;
            $('#selectAllCheckbox3').prop('checked', allChecked);
        });
    });
</script>
{% endblock body %}

templates/staff/Staffadd.html
{% extends 'main.html' %}


{% block title %}
    Staff Creat News
{% endblock title %}


{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}

<form action="" method="post">
{% csrf_token %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 border p-0 ">
                <div class="p-3">
                    {{a1.as_div}}
                </div>
                <button class="btn btn-outline-dark rounded-0 w-100 " type="submit">
                    submit
                </button> 
            </div>
        </div>
    </div>
</form>

<div class="p-5 m-5"></div>
<div class="p-5 m-5"></div>
<script>
    $('input').addClass('form-control  ');
    $('textarea').addClass('form-control  ');
    $('label').addClass('form-label  ');
    $('select').addClass('form-select  ');
</script>




<div class="p-5 m-5"></div>
{% endblock body %}

templates/staff/Staffcreate2.html
{% extends 'main.html' %}


{% block title %}  Staff CreatDate 2
{% endblock title %}
{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
    <div class="col-1 p-5 "></div>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-6 border border-5 rounded p-2" style="border-style: dotted !important;">
                <b>
                    Ganders: 
                    
                </b>
                <br>
                <label class="form-check-label" for="Male">Male: </label><input   checked  class="form-check-input"  value="Male" type="radio" name="Ganders" id="Male"> <br>
                <label class="form-check-label" for="Female">Female: </label><input   class="form-check-input"  value="Female" type="radio" name="Ganders" id="Female"> <br>
                <label class="form-check-label" for="Other">Other: </label><input   class="form-check-input"  value="Other" type="radio" name="Ganders" id="Other"> <br>
                <div class="col-12 sd8921">
                    {{forms.as_div}}
                </div>
                <div class="col-12 mt-3">
                    <center>
                        <button class="btn btn-primary" type="submit"> <i class="bi bi-cloud-arrow-up-fill"></i> Submit</button>
                    </center>
                </div>
            </div>
        </div>
    </div>
</form>

    
    <script>
        $("#id_user").val('{{user.id}}'); 
        $("#id_user").hide()
        $("textarea").addClass("form-control");
        $("#id_ZipCode").addClass("form-control");
        $("#id_PhoneNumber").addClass("form-control");
        $("#id_staff_name").addClass("form-control");
$("#id_DateOfBirth").addClass("form-control");
$("select").addClass("form-select");
$('#id_DateOfBirth').attr('type', 'date');
$('#id_JoinDate').attr('type', 'date');
$('#id_LeaveDate').attr('type', 'date');
$('#id_picture').addClass("form-control");
$('#id_JoinDate').addClass("form-control");
$('#id_LeaveDate').addClass("form-control");
$('label').addClass("fw-bold");
$("#id_staff_name").val("{{user}}");

</script>
<style>
    select{
        width: auto;
    }
    select > * {
  width: 200px !important;  /* Sets a fixed width */
text-wrap: wrap !important;
}
.sd8921 > div:nth-child(1){
    display: none;
}
    .sd8921 > div{
        padding-top: 20px;
        padding-bottom: 20px;
        border-bottom-style: dotted !important;
        border-bottom: solid gray ;
    }
</style>
<div class="col-1 m-5 p-5"></div>
{% endblock body %}

templates/staff/Topic.html
 {% extends 'main.html' %}


{% block title %}
    {{newsdb.NewsTitle}}
{% endblock title %}
{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}
{% endblock body %}

templates/staff/Writerssomeone.html
{% extends 'main.html' %}


{% block title %}

{% if yas == 1 %}
Writers
{% else %}
Editors 
{% endif %}

{% endblock title %}


{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}
<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<div class="container-fluid">
<div class="row justify-content-center">
<div class="border rounded col-6 p-3 mt-5">
    <table class="table">
       
        <thead>
            <tr>
                <td>
                    <input class="form-control" id="myInput" type="text" placeholder="Search..">
                </td>
            </tr>
            <tr>
                <th class="bg-dark text-white">
                    Name
                </th>
            </tr>
        </thead>
        <tbody  id="myTable">
            
            {% for x in userdball  %}
                <tr>
                    <td>
                        
                        {% if yas == 1  %}
                            
                        
                        <a href="/panelstaff/somewriter/{{Newsdb.id}}/{{x.staff_name}}/{{x.id}}">
                            {{x.staff_name}}
                        </a>
                        {% endif %}
                        
                        {% if yas == 0 %}
                               
                        <a href="/panelstaff/editorsome/{{Newsdb.id}}/{{x.staff_name}}/{{x.id}}">
                            {{x.staff_name}}
                        </a>
                        {% endif %}
                            
                    </td>
                </tr>
            {% endfor %}
                
        </tbody>
    </table>
</div>
</div>
</div>

{% endblock body %}
    

templates/staff/creatdbtbale.html
{% extends 'main.html' %}


{% block title %}
    Create DB
{% endblock title %}
{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}

<div class="container-fluid">
<div class="row justify-content-center ">
<div class="col-6">
<!--  -->
<table class="table mt-5 table-bordered ">
    <thead>
        <tr >
            <th colspan="2" class="bg-dark text-white text-center ">
                Create DB <i class="bi bi-database-fill-add"></i>
            </th>
        </tr>
        <tr>
            <th>
                Name
            </th>
            <th class="text-center" style="width: 10%;">
                Create
            </th>
        </tr>
    </thead>
    <tr>
        <td>
            <a href="{% url 'Newsdbcreats' %}">
                News 
            </a>
        </td>
        <td class="text-center">
            <a href="{% url 'Newsdbcreats' %}"  >
                <i class="bi bi-database-fill-add"></i>
            </a>
        </td>
    </tr>
    <tr>
        <td>
            <a href="{% url 'topicecreatdb' %}">
                Topic
            </a>
        </td>
        <td class="text-center">
            <a href="{% url 'topicecreatdb' %}">
                 <i class="bi bi-database-fill-add"></i>
            </a>
        </td>
    </tr>
    
    {% if userdb.position in 'Manager,Admin,CEO'  %}
    <tr>
        <td>
            Create Staff
        </td>
        <td class="text-center">
              <a href="{% url 'Staffcreate' %}">
                 <i class="bi bi-database-fill-add"></i>
            </a>

        </td>
    </tr> 
    {% endif %}
        
 
    
</table>
<!--  -->
</div>
</div>
</div>


{% endblock body %}

templates/staff/datalist.html
{% extends 'main.html' %}


{% block title %}
    Data List
{% endblock title %}


{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}
<div class="container-fluid">
<div class="row justify-content-center">
<div class="col-6 mt-5">

  <table class="table table-bordered ">
    <thead>

      <tr>
        <th class=" bg-dark text-white fs-4 ">  News Not Submit </th>
        <th class=" bg-dark text-white fs-4 text-center" style="width: 75px;">Edit</th>
        <th class=" bg-dark text-white fs-4 text-center" style="width: 75px;">Submit</th>
        <th class=" bg-dark text-white fs-4 text-center" style="width: 75px;">Rejected</th>
      </tr>
    </thead>

    
    {% for c  in newsgb  %}
      
    
    {% if c.JournalistsPermission == None %}
      
    
    <tr>
      <td><a href=""> {{c.NewsTitle}} </a></td>
      <td class="text-center  "> <a href=""> <i class="bi bi-pencil-square"></i> </a> </td>
      <td class="text-center  "> <a href=""> <i class="bi bi-upload"></i>  </a> </td>
      <td class="text-center  "> <a href=""> <i class="bi bi-ban"></i>  </a> </td>
    </tr>    
    {% endif %}
    {% endfor %}

  </table>
<!--  -->


<style>
    a:hover{
        color: red;
        font-weight: bolder;
    }
</style>

</div>
</div>
</div>
{% endblock body %}
    

templates/staff/editnews.html
{% extends 'main.html' %}


{% block title %}
    {{newsdb.NewsTitle}}
{% endblock title %}
{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-6 mt-5 border rounded p-3 shadow-lg">
            <div class="row">
                <div class="text-end" style="font-size: 32px;">
                   
                    <a href="/panelstaff/data/list/">
                        <i class="bi bi-x-lg"></i>
                    </a>
                </div>
                <form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="col-12  ">
        <div class="row">
            <div class="col-12">
                <label for="topic"  class="form-label" >Topic:</label>
                
                <select required  name="topic" class="  form-select form-control" id="topic">
                    <option value="{{newsdb.Topic.id}}">{{newsdb.Topic}}  </option>
                    {% for x in topic  %}
                    <option value="{{x.id}}"> {{x.Topic}} </option>
                    {% endfor %}
                    
                </select>
            </div>

            <div class="col-12">
                <label for="Title"  class="form-label" >Title:</label>
                <input type="text" name="Title" value="{{newsdb.NewsTitle}}" id="Title" required class="form-control">
            </div>
    <div class="col-12">
        <label for="myEditor" class="form-label">explained</label>
        <textarea name="myEditor" rows="15"class="w-100 form-control " id="myEditor">
        {{newsdb.Txt}}
    </textarea>
    <textarea id="myTextarea" name="explaine" hidden rows="5" cols="50"></textarea>

   <script>
    $(document).ready(function(){
        $("#button1").click(function(){
            const editorContent = editor.getContents();
            $("#myTextarea").val(editorContent);
        })
    })
   </script>
    <script>
        const editor = SUNEDITOR.create('myEditor', {
            buttonList: [['undo', 'redo'],['formatBlock'],['bold', 'underline', 'italic', 'strike'],['fontColor', 'hiliteColor'],['align', 'list', 'table'],[],['fullScreen', 'codeView']
            ]
        });
    
    </script>
            </div>
            <div class="col-12 mt-2">
                {{NewsImagedbform.as_div}}
                <br>
                
                {% for x in  multipleNewsImageAndVideodb %}
                  image:  <a href="/panelstaff/multipleim/{{x.id}}/{{x.news.id}}"> {{x.image}} <span><i class="bi bi-pencil-square"></i></span> </a> <br>
                  video:  <a href="/panelstaff/multipleim/{{x.id}}/{{x.news.id}}"> {{x.video}} {% if x.video == "" %}none {% else %} {% endif %}<span><i class="bi bi-pencil-square"></i></span> </a> 
                        
                </a> <br>
                {% endfor %}
                    
            </div>
            <div class="col-12 mt-3 mb-0">
               <div class="col-12 pb-3">
                            <label for="onlyvideo">onlyvideo</label>
                            
                            
                            {% if newsdb.onlyvideo == True  %}
                            <input type="checkbox"  name="onlyvideo" checked id="onlyvideo">
                            {% else %}
    <input type="checkbox"  name="onlyvideo"  id="onlyvideo">
                                
                            {% endif %}
                                
                        </div>
                <button id="button1" class="btn btn-outline-dark" type="submit">
                    
                    {% if request.path == '/panelstaff/Newsdbcreats/' %}
                        Creat
                        {% else %}
                        Save
                    {% endif %}
                        
                </button>
            </div>
            
        </div>
    </div>

</div>
</div>
</form>
</div>
</div>


<script>
    $(document).ready(function(){
        $("#id_Image").addClass('form-control');
        $("#id_Video").addClass('form-control');
    })
</script>

<div class="p-5 m-5 "></div>

{% endblock body %}

templates/staff/topicecreatdb.html
{% extends 'main.html' %}


{% block title %}
    Create Topic
{% endblock title %}
{% block body %}
{% include 'staff/nav.html' with userdb=userdb %}

<div class="container-fluid">
    <form action="" method="post">
        {% csrf_token %}
<div class="row justify-content-center">
    <div class="col-6 shadow-lg border rounded mt-5 p-3 ">
        <div class="text-end" style="font-size: 32px;">
                   
                    <a href="/panelstaff/">
                        <i class="bi bi-x-lg"></i>
                    </a>
                </div>
            <label for="topic">Topic</label>
            <input name="topic" id="topic" type="text" placeholder="Entert har..." maxlength="20" required class="form-control">
            <div>

                <button type="submit" class=" btn mt-3 btn-dark">
                    Submit
                </button>
            </div>
        </div>
    </div>
</form>
</div>

{% endblock body %}

